name = "CyclicArrays"
uuid = "6023044f-b3ef-4c22-8399-3ec90a0c9b75"
authors = ["udistr <udistr@gmail.com>"]
version = "0.4.3"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
